import 'package:flutter/material.dart';
import 'package:flutter_bloc/flutter_bloc.dart';
import 'package:transportation_app/core/l10n/locale_cubit.dart';
import 'package:transportation_app/core/l10n/app_localizations.dart';

extension Navigation on BuildContext {
  Future<dynamic> pushNamed(String route, {Object? arguments}) {
    return Navigator.of(this).pushNamed(route, arguments: arguments);
  }

  Future<dynamic> pushReplacementNamed(String route, {Object? arguments}) {
    return Navigator.of(this).pushReplacementNamed(route, arguments: arguments);
  }

  Future<dynamic> pushNamedAndRemoveuntil(
    String route, {
    Object? arguments,
    required RoutePredicate predicate,
  }) {
    return Navigator.of(
      this,
    ).pushNamedAndRemoveUntil(route, predicate, arguments: arguments);
  }

  void pop() => Navigator.of(this).pop();
}

extension LocaleHelper on BuildContext {
  bool get isArabic => read<LocaleCubit>().isArabic;
}

extension GovernorateHelper on String {
  String toLocalizedGov(BuildContext context) {
    if (!context.isArabic) return this;
    final l10n = AppLocalizations.of(context);
    if (l10n == null) return this;
    switch (toLowerCase()) {
      case 'cairo':
        return l10n.gov_Cairo;
      case 'alexandria':
        return l10n.gov_Alexandria;
      case 'giza':
        return l10n.gov_Giza;
      case 'aswan':
        return l10n.gov_Aswan;
      case 'luxor':
        return l10n.gov_Luxor;
      case 'minya':
        return l10n.gov_Minya;
      case 'beheira':
        return l10n.gov_Beheira;
      case 'qena':
        return l10n.gov_Qena;
      case 'sohag':
        return l10n.gov_Sohag;
      // Handle both API spellings: 'Assiut' (JSON) and 'Asyut' (legacy)
      case 'asyut':
      case 'assiut':
        return l10n.gov_Asyut;
      case 'fayoum':
        return l10n.gov_Fayoum;
      case 'beni suef':
        return l10n.gov_BeniSuef;
      case 'sharqia':
        return l10n.gov_Sharqia;
      case 'dakahlia':
        return l10n.gov_Dakahlia;
      // Handle both API spellings: 'Gharbia' (JSON) and 'Gharbiya' (legacy)
      case 'gharbiya':
      case 'gharbia':
        return l10n.gov_Gharbiya;
      case 'kafr el sheikh':
        return l10n.gov_KafrElSheikh;
      case 'monufia':
        return l10n.gov_Monufia;
      case 'qalyubia':
        return l10n.gov_Qalyubia;
      case 'ismailia':
        return l10n.gov_Ismailia;
      case 'suez':
        return l10n.gov_Suez;
      case 'damietta':
        return l10n.gov_Damietta;
      // Previously missing governorates
      case 'matrouh':
        return l10n.gov_Matrouh;
      case 'port said':
        return l10n.gov_PortSaid;
      default:
        return this;
    }
  }
}

// Map from English sub-governorate name (lowercase) to Arabic
const Map<String, String> _subGovEnToAr = {
  'aba wakf': 'ابا الوقف',
  'abo ghaleb': 'ابو غالب',
  'abo gresh': 'ابو جريش',
  'abo hammad': 'ابو حماد',
  'abo homos': 'ابو حمص',
  'abo khawi': 'ابو الخاوي',
  'abo kibir': 'ابو كبير',
  'abo mashhour': 'ابو مشهور',
  'abo qurqas': 'ابو قرقاص',
  'abo shousha': 'ابو شوشة',
  'abo shuquq': 'ابو الشقوق',
  'abo sultan': 'ابو سلطان',
  'abo swer': 'ابو صوير',
  'abo tesht': 'ابو تشت',
  'abo tij': 'ابو تيج',
  'abo yassin': 'ابو ياسين',
  'adawyh': 'العداوية',
  'akhmas': 'الاخماس',
  'al-azhar university': 'جامعة الأزهر',
  'alamein': 'العلمين',
  'alexandria': 'الاسكندرية',
  'ameed': 'العميد',
  'amereyat el fayoum': 'عامرية الفيوم',
  'amreyah': 'العامرية',
  'arab raml': 'عرب الرمل',
  'armant': 'ارمنت',
  'ashmant': 'اشمنت',
  'ashmun': 'اشمون',
  'asluji': 'العصلوجي',
  'assiut': 'اسيوط',
  'aswan': 'اسوان',
  'atwab': 'اطواب',
  'awlad seif': 'اولاد سيف',
  'ayat': 'العياط',
  'az zanklun': 'الزنكلون',
  'aziziyyah': 'العزيزية',
  'baalwh': 'البعالوة',
  'badawy': 'بدوي',
  'badr mosque': 'جامع بدر',
  'badrshein': 'البدرشين',
  'ballana': 'بلانة',
  'balyana': 'البلينا',
  'banha': 'بنها',
  'baqliyyah': 'البقلية',
  'bardein': 'بردين',
  'bardis': 'برديس',
  'barqin': 'برقين',
  'bartas': 'برطس',
  'basandilah': 'بسنديله',
  'bashtil': 'بشتيل المحطة',
  'bashtil b': 'بشتيل البلد',
  'batanun': 'البتانون',
  'belbes': 'بلبيس',
  'belkas': 'بلقاس',
  'beni hidayr': 'بني حدير',
  'beni mazar': 'بني مزار',
  'beni salamah': 'بني سلامة',
  'beni suef': 'بني سويف',
  'berket saba': 'بركة السبع',
  'biba': 'ببا',
  'bir imarah': 'بير عمارة',
  'birijat': 'البريجات',
  'birqash': 'برقاش',
  'biyala': 'بيلا',
  'blida': 'البليدة',
  'borg el arab': 'برج العرب',
  'borg el arab airport': 'مطار برج العرب',
  'bouha': 'البوها',
  'cairo': 'القاهرة',
  'dabaa': 'الضبعة',
  'damanhour': 'دمنهور',
  'damaris': 'دماريس',
  'damietta': 'دمياط',
  'daraw': 'دراو',
  'dayr mawas': 'دير مواس',
  'dayrout': 'ديروط',
  'derwah': 'دروة',
  'desouk': 'دسوق',
  'dishna': 'دشنا',
  'ebshway': 'ابشواي',
  'edfu': 'ادفو',
  'edwah': 'العدوة',
  'el mahalla el kubra': 'المحلة الكبرى',
  'esna': 'اسنا',
  'ethaad': 'الاتحاد',
  'farshut': 'فرشوط',
  'fashn': 'الفشن',
  'fayed': 'فايد',
  'fayoum': 'الفيوم',
  'fokah': 'فوكة',
  'galaa camp': 'معسكر الجلاء',
  'galal': 'جلال',
  'gelatmah': 'الجلاتمة',
  'gezira wastanih': 'الجزيرة الوسطانية',
  'girga': 'جرجا',
  'giza': 'الجيزة',
  'hadrah': 'الحضرة',
  'hammam': 'الحمام',
  'hamoul': 'الحامول',
  'harayah raznah': 'هرية رزنة',
  'hawamdeyya': 'الحوامدية',
  'hihya': 'هيها',
  'hikal basha': 'هيكل باشا',
  'hilwasi': 'الحلواصي',
  'hilwasi b': 'الحلواصي البلد',
  'ibshan': 'ابشان',
  'inshas': 'انشاص',
  'ismailia': 'الاسماعيلية',
  'itay barud': 'ايتاي البارود',
  'jadidah': 'الجديدة',
  'jenefh': 'جنيفة',
  'kafr ammar': 'كفر عمار',
  'kafr batanun': 'كفر البتانون',
  'kafr bulin': 'كفر بولين',
  'kafr dawar': 'كفر الدوار',
  'kafr dawoud': 'كفر داود',
  'kafr el sheikh': 'كفر الشيخ',
  'kafr msalamya': 'كفر المسلمية',
  'kafr ramadah': 'كفر رمادة',
  'kafr saad': 'كفر سعد',
  'kafr sanabisah': 'كفر السنابسة',
  'kafr saqr': 'كفر صقر',
  'kafr sarawah': 'كفر صراوة',
  'kafr selim': 'كفر سليم',
  'kafr shebeen': 'كفر شبين',
  'kafr tabluha': 'كفر طبلوها',
  'kafr taha': 'كفر طحا',
  'kafr zayat': 'كفر الزيات',
  'kajuj': 'كاجوج',
  'kalabsha': 'كلابشة',
  'kamshush': 'كمشوش',
  'khatatbah': 'الخطاطبة',
  'kom abo rady': 'كوم أبو راضي',
  'kom ahmar': 'الكوم الاحمر',
  'kom halin': 'كوم حلين',
  'kom hamada': 'كوم حمادة',
  'kom ombo': 'كوم امبو',
  'kom taweel': 'الكوم الطويل',
  'luxor': 'الاقصر',
  'maghagha': 'مغاغة',
  'mahallat mousa': 'محلة موسى',
  'mahallat rouh': 'محلة روح',
  'mahallat subk': 'محلة سبك',
  'mahamid': 'المحاميد',
  'mahjar abo hammad': 'محجر ابو حماد',
  'mahsmh': 'المحسمة',
  'mallawi': 'ملوي',
  'manashi': 'المناشي',
  'manfalut': 'منفلوط',
  'manqabad': 'منقباد',
  'manshyt bakry': 'منشية البكري',
  'mansoura': 'المنصورة',
  'maragha': 'المراغة',
  'maraziq': 'المرازيق',
  'marsa matruh': 'مرسى مطروح',
  'mashtul': 'مشتول',
  'matanyah': 'المتانية',
  'matay': 'مطاي',
  'maymun': 'الميمون',
  'mazghounah': 'المزغونة',
  'meet halfa': 'ميت حلفا',
  'menyet qamh': 'منية القمح',
  'menyet sebaa': 'منية السباع',
  'minuf': 'منوف',
  'minya': 'المنيا',
  'minyat shentena ayash': 'منية شنتا عياش',
  'mit assas': 'ميت عساس',
  'mit ghamer': 'ميت غمر',
  'mit qayed': 'ميت القايد',
  'mit yazid': 'ميت يزيد',
  'modiriyat tahrir': 'مديرية التحرير',
  'mohamed baghdady': 'محمد البغدادي',
  'moharam beek': 'محرم بك',
  'monshaa': 'المنشأة',
  'monshaat abo rayyah': 'منشاة ابو رية',
  'monshaat kiram': 'منشأة الكرام',
  'murabian': 'المرابعين',
  'nafesha': 'نفيشة',
  'nagaa hammadi': 'نجع حمادي',
  'naqidi': 'النقيدي',
  'nashart': 'نشرت',
  'nasiriyah': 'الناصرية',
  'nasser': 'ناصر',
  'nawa': 'نوى',
  'nazlet khayal': 'نزلة الخيال',
  'niklah': 'نكلا',
  'ossim': 'اوسيم',
  'port said': 'بورسعيد',
  'qaha': 'قها',
  'qalyoub': 'قليوب',
  'qalyoub b': 'قليوب البلد',
  'qanatir n': 'القناطر ج',
  'qantara gharb': 'القنطرة غرب',
  'qaraqrah': 'القراقرة',
  'qassasin': 'القصاصين',
  'qata': 'القطا',
  'qata b': 'القطا البلد',
  'qena': 'قنا',
  'qift': 'قفط',
  'qilishan': 'قليشان',
  'qleen': 'قلين',
  'qleen b': 'قلين البلد',
  'qotouri': 'القطورى',
  'qotur': 'قطور',
  'quesna': 'قويسنا',
  'qus': 'قوص',
  'qusiyyah': 'القوصية',
  'radisia': 'الرديسية',
  'ragdiah': 'الرجدية',
  'ramadi': 'الرمادي',
  'ramlat injib': 'رملة الأنجب',
  'raqqah': 'الرقة',
  'ras el hekma': 'راس الحكمة',
  'ras khaleej': 'راس الخليج',
  'rawda': 'الروضة',
  'rous': 'الروس',
  'rowaysat': 'الرويسات',
  'saft hinnah': 'صفط الحنة',
  'saft inab': 'صفط العنب',
  'saft turab': 'صفط تراب',
  'sakha': 'سخا',
  'salamant': 'سلمنت',
  'samadun': 'سمادون',
  'samalut': 'سملوط',
  'samannoud': 'سمنود',
  'samla': 'سملا',
  'sandanhour': 'سندنهور',
  'sandub': 'سندوب',
  'sanhur': 'سنهور',
  'santa': 'السنطة',
  'sawah': 'الصوة',
  'segin': 'سجين',
  'senbellawein': 'السنبلاوين',
  'serapeum': 'سرابيوم',
  'shabanat': 'الشبانات',
  'shalaqan': 'شلقان',
  'shama': 'شما',
  'shanawan': 'شنوان',
  'sharawnah': 'الشراونة',
  'shatanof': 'شطانوف',
  'shawah': 'شاوة',
  'shbas': 'شباس',
  'shebeen kom n': 'شبين الكوم ج',
  'shebeen kom o': 'شبين الكوم ق',
  'shebshir hessah': 'شبشير الحصة',
  'sheikh zayed': 'الشيخ زايد',
  'shibin qanatir': 'شبين القناطر',
  'shiblanjah': 'شبلنجة',
  'shin': 'الشين',
  'shirbin': 'شربين',
  'shirshimah': 'شرشيمة',
  'shobra qubala': 'شبرا قبالة',
  'shubra el kheima': 'شبرا الخيمة',
  'sibaiyyah': 'السباعية',
  'sidfa': 'صدفا',
  'sidi abdel rahman': 'سيدي عبد الرحمن',
  'sidi gaber': 'سيدي جابر',
  'sidi ghazy': 'سيدي غازي',
  'sidi henash': 'سيدي حنيش',
  'sila': 'سيلا',
  'silwa bahari': 'سلوا',
  'sohag': 'سوهاج',
  'suds': 'سدس',
  'suez': 'السويس',
  'tafhna ashraf': 'تفهنا الاشراف',
  'taha bishah': 'طحا البيشة',
  'tahanub': 'طحانوب',
  'tahta': 'طهطا',
  'tairyyah': 'الطيرية',
  'tairyyah b': 'الطيرية البلد',
  'tal kabeer': 'التل الكبير',
  'tala': 'تلا',
  'talkha': 'طلخا',
  'tall rozan': 'تل روزن',
  'tanbadi': 'طنبدي',
  'tansa': 'طنسا',
  'tanta': 'طنطا',
  'taranis arab': 'طرانيس العرب',
  'tarranah': 'الطرانة',
  'tawfiqiah': 'التوفيقية',
  'tima': 'طما',
  'toukh': 'طوخ',
  'upper egypt': 'صعيد مصر',
  'usayrat': 'العسيرات',
  'waqid': 'واقد',
  'wasfih': 'الواصفية',
  'wasta': 'الواسطى',
  'werash': 'الورش',
  'werdan': 'وردان',
  'zagazig': 'الزقازيق',
  'zagazig university': 'جامعة الزقازيق',
  'zahawiyin': 'الزهوين',
  'zat kom': 'ذات الكوم',
  'zawya hamraa': 'الزاوية الحمراء',
  'zaytoun q': 'الزيتون ق',
  'zefta': 'زفتى',
  'zurayqi': 'الزريقي',
};

// Map from Arabic sub-governorate name to English
const Map<String, String> _subGovArToEn = {
  'ابا الوقف': 'Aba Wakf',
  'ابشان': 'Ibshan',
  'ابشواي': 'Ebshway',
  'ابو الخاوي': 'Abo Khawi',
  'ابو الشقوق': 'Abo Shuquq',
  'ابو تشت': 'Abo Tesht',
  'ابو تيج': 'Abo Tij',
  'ابو جريش': 'Abo Gresh',
  'ابو حماد': 'Abo Hammad',
  'ابو حمص': 'Abo Homos',
  'ابو سلطان': 'Abo Sultan',
  'ابو شوشة': 'Abo Shousha',
  'ابو صوير': 'Abo Swer',
  'ابو غالب': 'Abo Ghaleb',
  'ابو قرقاص': 'Abo Qurqas',
  'ابو كبير': 'Abo Kibir',
  'ابو مشهور': 'Abo Mashhour',
  'ابو ياسين': 'Abo Yassin',
  'ادفو': 'Edfu',
  'ارمنت': 'Armant',
  'اسنا': 'Esna',
  'اسوان': 'Aswan',
  'اسيوط': 'Assiut',
  'اشمنت': 'Ashmant',
  'اشمون': 'Ashmun',
  'اطواب': 'Atwab',
  'الاتحاد': 'Ethaad',
  'الاخماس': 'Akhmas',
  'الاسكندرية': 'Alexandria',
  'الاسماعيلية': 'Ismailia',
  'الاقصر': 'Luxor',
  'البتانون': 'Batanun',
  'البدرشين': 'Badrshein',
  'البريجات': 'Birijat',
  'البعالوة': 'Baalwh',
  'البقلية': 'Baqliyyah',
  'البليدة': 'Blida',
  'البلينا': 'Balyana',
  'البوها': 'Bouha',
  'التل الكبير': 'Tal Kabeer',
  'التوفيقية': 'Tawfiqiah',
  'الجديدة': 'Jadidah',
  'الجزيرة الوسطانية': 'Gezira Wastanih',
  'الجلاتمة': 'Gelatmah',
  'الجيزة': 'Giza',
  'الحامول': 'Hamoul',
  'الحضرة': 'Hadrah',
  'الحلواصي': 'Hilwasi',
  'الحلواصي البلد': 'Hilwasi B',
  'الحمام': 'Hammam',
  'الحوامدية': 'Hawamdeyya',
  'الخطاطبة': 'Khatatbah',
  'الرجدية': 'Ragdiah',
  'الرديسية': 'Radisia',
  'الرقة': 'Raqqah',
  'الرمادي': 'Ramadi',
  'الروس': 'Rous',
  'الروضة': 'Rawda',
  'الرويسات': 'Rowaysat',
  'الزاوية الحمراء': 'Zawya Hamraa',
  'الزريقي': 'Zurayqi',
  'الزقازيق': 'Zagazig',
  'الزنكلون': 'Az Zanklun',
  'الزهوين': 'Zahawiyin',
  'الزيتون ق': 'Zaytoun Q',
  'السباعية': 'Sibaiyyah',
  'السنبلاوين': 'Senbellawein',
  'السنطة': 'Santa',
  'السويس': 'Suez',
  'الشبانات': 'Shabanat',
  'الشراونة': 'Sharawnah',
  'الشيخ زايد': 'Sheikh Zayed',
  'الشين': 'Shin',
  'الصوة': 'Sawah',
  'الضبعة': 'Dabaa',
  'الطرانة': 'Tarranah',
  'الطيرية': 'Tairyyah',
  'الطيرية البلد': 'Tairyyah B',
  'العامرية': 'Amreyah',
  'العداوية': 'Adawyh',
  'العدوة': 'Edwah',
  'العزيزية': 'Aziziyyah',
  'العسيرات': 'Usayrat',
  'العصلوجي': 'Asluji',
  'العلمين': 'Alamein',
  'العميد': 'Ameed',
  'العياط': 'Ayat',
  'الفشن': 'Fashn',
  'الفيوم': 'Fayoum',
  'القاهرة': 'Cairo',
  'القراقرة': 'Qaraqrah',
  'القصاصين': 'Qassasin',
  'القطا': 'Qata',
  'القطا البلد': 'Qata B',
  'القطورى': 'Qotouri',
  'القناطر ج': 'Qanatir N',
  'القنطرة غرب': 'Qantara Gharb',
  'القوصية': 'Qusiyyah',
  'الكوم الاحمر': 'Kom Ahmar',
  'الكوم الطويل': 'Kom Taweel',
  'المتانية': 'Matanyah',
  'المحاميد': 'Mahamid',
  'المحسمة': 'Mahsmh',
  'المحلة الكبرى': 'El Mahalla El Kubra',
  'المرابعين': 'Murabian',
  'المرازيق': 'Maraziq',
  'المراغة': 'Maragha',
  'المزغونة': 'Mazghounah',
  'المناشي': 'Manashi',
  'المنشأة': 'Monshaa',
  'المنصورة': 'Mansoura',
  'المنيا': 'Minya',
  'الميمون': 'Maymun',
  'الناصرية': 'Nasiriyah',
  'النقيدي': 'Naqidi',
  'الواسطى': 'Wasta',
  'الواصفية': 'Wasfih',
  'الورش': 'Werash',
  'انشاص': 'Inshas',
  'اوسيم': 'Ossim',
  'اولاد سيف': 'Awlad Seif',
  'ايتاي البارود': 'Itay Barud',
  'ببا': 'Biba',
  'بدوي': 'Badawy',
  'برج العرب': 'Borg El Arab',
  'برديس': 'Bardis',
  'بردين': 'Bardein',
  'برطس': 'Bartas',
  'برقاش': 'Birqash',
  'برقين': 'Barqin',
  'بركة السبع': 'Berket Saba',
  'بسنديله': 'Basandilah',
  'بشتيل البلد': 'Bashtil B',
  'بشتيل المحطة': 'Bashtil',
  'بلانة': 'Ballana',
  'بلبيس': 'Belbes',
  'بلقاس': 'Belkas',
  'بنها': 'Banha',
  'بني حدير': 'Beni Hidayr',
  'بني سلامة': 'Beni Salamah',
  'بني سويف': 'Beni Suef',
  'بني مزار': 'Beni Mazar',
  'بورسعيد': 'Port Said',
  'بير عمارة': 'Bir Imarah',
  'بيلا': 'Biyala',
  'تفهنا الاشراف': 'Tafhna Ashraf',
  'تل روزن': 'Tall Rozan',
  'تلا': 'Tala',
  'جامع بدر': 'Badr Mosque',
  'جامعة الأزهر': 'Al-Azhar University',
  'جامعة الزقازيق': 'Zagazig University',
  'جرجا': 'Girga',
  'جلال': 'Galal',
  'جنيفة': 'Jenefh',
  'دراو': 'Daraw',
  'دروة': 'Derwah',
  'دسوق': 'Desouk',
  'دشنا': 'Dishna',
  'دماريس': 'Damaris',
  'دمنهور': 'Damanhour',
  'دمياط': 'Damietta',
  'دير مواس': 'Dayr Mawas',
  'ديروط': 'Dayrout',
  'ذات الكوم': 'Zat Kom',
  'راس الحكمة': 'Ras El Hekma',
  'راس الخليج': 'Ras Khaleej',
  'رملة الأنجب': 'Ramlat Injib',
  'زفتى': 'Zefta',
  'سجين': 'Segin',
  'سخا': 'Sakha',
  'سدس': 'Suds',
  'سرابيوم': 'Serapeum',
  'سلمنت': 'Salamant',
  'سلوا': 'Silwa Bahari',
  'سمادون': 'Samadun',
  'سملا': 'Samla',
  'سملوط': 'Samalut',
  'سمنود': 'Samannoud',
  'سندنهور': 'Sandanhour',
  'سندوب': 'Sandub',
  'سنهور': 'Sanhur',
  'سوهاج': 'Sohag',
  'سيدي جابر': 'Sidi Gaber',
  'سيدي حنيش': 'Sidi Henash',
  'سيدي عبد الرحمن': 'Sidi Abdel Rahman',
  'سيدي غازي': 'Sidi Ghazy',
  'سيلا': 'Sila',
  'شاوة': 'Shawah',
  'شباس': 'Shbas',
  'شبرا الخيمة': 'Shubra El Kheima',
  'شبرا قبالة': 'Shobra Qubala',
  'شبشير الحصة': 'Shebshir Hessah',
  'شبلنجة': 'Shiblanjah',
  'شبين القناطر': 'Shibin Qanatir',
  'شبين الكوم ج': 'Shebeen Kom N',
  'شبين الكوم ق': 'Shebeen Kom O',
  'شربين': 'Shirbin',
  'شرشيمة': 'Shirshimah',
  'شطانوف': 'Shatanof',
  'شلقان': 'Shalaqan',
  'شما': 'Shama',
  'شنوان': 'Shanawan',
  'صدفا': 'Sidfa',
  'صعيد مصر': 'Upper Egypt',
  'صفط الحنة': 'Saft Hinnah',
  'صفط العنب': 'Saft Inab',
  'صفط تراب': 'Saft Turab',
  'طحا البيشة': 'Taha Bishah',
  'طحانوب': 'Tahanub',
  'طرانيس العرب': 'Taranis Arab',
  'طلخا': 'Talkha',
  'طما': 'Tima',
  'طنبدي': 'Tanbadi',
  'طنسا': 'Tansa',
  'طنطا': 'Tanta',
  'طهطا': 'Tahta',
  'طوخ': 'Toukh',
  'عامرية الفيوم': 'Amereyat El Fayoum',
  'عرب الرمل': 'Arab Raml',
  'فايد': 'Fayed',
  'فرشوط': 'Farshut',
  'فوكة': 'Fokah',
  'قطور': 'Qotur',
  'قفط': 'Qift',
  'قليشان': 'Qilishan',
  'قلين': 'Qleen',
  'قلين البلد': 'Qleen B',
  'قليوب': 'Qalyoub',
  'قليوب البلد': 'Qalyoub B',
  'قنا': 'Qena',
  'قها': 'Qaha',
  'قوص': 'Qus',
  'قويسنا': 'Quesna',
  'كاجوج': 'Kajuj',
  'كفر البتانون': 'Kafr Batanun',
  'كفر الدوار': 'Kafr Dawar',
  'كفر الزيات': 'Kafr Zayat',
  'كفر السنابسة': 'Kafr Sanabisah',
  'كفر الشيخ': 'Kafr El Sheikh',
  'كفر المسلمية': 'Kafr Msalamya',
  'كفر بولين': 'Kafr Bulin',
  'كفر داود': 'Kafr Dawoud',
  'كفر رمادة': 'Kafr Ramadah',
  'كفر سعد': 'Kafr Saad',
  'كفر سليم': 'Kafr Selim',
  'كفر شبين': 'Kafr Shebeen',
  'كفر صراوة': 'Kafr Sarawah',
  'كفر صقر': 'Kafr Saqr',
  'كفر طبلوها': 'Kafr Tabluha',
  'كفر طحا': 'Kafr Taha',
  'كفر عمار': 'Kafr Ammar',
  'كلابشة': 'Kalabsha',
  'كمشوش': 'Kamshush',
  'كوم أبو راضي': 'Kom Abo Rady',
  'كوم امبو': 'Kom Ombo',
  'كوم حلين': 'Kom Halin',
  'كوم حمادة': 'Kom Hamada',
  'محجر ابو حماد': 'Mahjar Abo Hammad',
  'محرم بك': 'Moharam Beek',
  'محلة روح': 'Mahallat Rouh',
  'محلة سبك': 'Mahallat Subk',
  'محلة موسى': 'Mahallat Mousa',
  'محمد البغدادي': 'Mohamed Baghdady',
  'مديرية التحرير': 'Modiriyat Tahrir',
  'مرسى مطروح': 'Marsa Matruh',
  'مشتول': 'Mashtul',
  'مطار برج العرب': 'Borg El Arab Airport',
  'مطاي': 'Matay',
  'معسكر الجلاء': 'Galaa Camp',
  'مغاغة': 'Maghagha',
  'ملوي': 'Mallawi',
  'منشأة الكرام': 'Monshaat Kiram',
  'منشاة ابو رية': 'Monshaat Abo Rayyah',
  'منشية البكري': 'Manshyt Bakry',
  'منفلوط': 'Manfalut',
  'منقباد': 'Manqabad',
  'منوف': 'Minuf',
  'منية السباع': 'Menyet Sebaa',
  'منية القمح': 'Menyet Qamh',
  'منية شنتا عياش': 'Minyat Shentena Ayash',
  'ميت القايد': 'Mit Qayed',
  'ميت حلفا': 'Meet Halfa',
  'ميت عساس': 'Mit Assas',
  'ميت غمر': 'Mit Ghamer',
  'ميت يزيد': 'Mit Yazid',
  'ناصر': 'Nasser',
  'نجع حمادي': 'Nagaa Hammadi',
  'نزلة الخيال': 'Nazlet Khayal',
  'نشرت': 'Nashart',
  'نفيشة': 'Nafesha',
  'نكلا': 'Niklah',
  'نوى': 'Nawa',
  'هرية رزنة': 'Harayah Raznah',
  'هيكل باشا': 'Hikal Basha',
  'هيها': 'Hihya',
  'واقد': 'Waqid',
  'وردان': 'Werdan',
};

extension SubGovernorateHelper on String {
  String toLocalizedSubGov(BuildContext context) {
    if (context.isArabic) {
      return _subGovEnToAr[toLowerCase()] ?? this;
    } else {
      return _subGovArToEn[this] ?? this;
    }
  }
}

const Map<String, String> _stationEnToAr = {
  'aba wakf': 'ابا الوقف',
  'abu tig': 'أبو تيج',
  'shatourah': 'شطورة',
  'balasfurah': 'بلصفورة',
  'nadi el seka': 'نادي السكة',
  'abd el qader': 'عبد القادر',
  'abo qir fertilizer': 'سماد أبو قير',
  'baheeg': 'بهيج',
  'abo ghaleb': 'ابو غالب',
  'abo gresh': 'ابو جريش',
  'abo hammad': 'ابو حماد',
  'abo homos': 'ابو حمص',
  'abo khawi': 'ابو الخاوي',
  'abo kibir': 'ابو كبير',
  'abo mashhour': 'ابو مشهور',
  'abo qurqas': 'ابو قرقاص',
  'abo shousha': 'ابو شوشة',
  'abo shuquq': 'ابو الشقوق',
  'abo sultan': 'ابو سلطان',
  'abo swer': 'ابو صوير',
  'abo tesht': 'ابو تشت',
  'abo tij': 'ابو تيج',
  'abo yassin': 'ابو ياسين',
  'adawyh': 'العداوية',
  'akhmas': 'الاخماس',
  'al-azhar university': 'جامعة الأزهر',
  'alamein': 'العلمين',
  'alexandria': 'الاسكندرية',
  'ameed': 'العميد',
  'amereyat el fayoum': 'عامرية الفيوم',
  'amreyah': 'العامرية',
  'arab raml': 'عرب الرمل',
  'armant': 'ارمنت',
  'ashmant': 'اشمنت',
  'ashmun': 'اشمون',
  'asluji': 'العصلوجي',
  'assiut': 'اسيوط',
  'aswan': 'اسوان',
  'atwab': 'اطواب',
  'awlad seif': 'اولاد سيف',
  'ayat': 'العياط',
  'az zanklun': 'الزنكلون',
  'aziziyyah': 'العزيزية',
  'baalwh': 'البعالوة',
  'badawy': 'بدوي',
  'badr mosque': 'جامع بدر',
  'badrshein': 'البدرشين',
  'ballana': 'بلانة',
  'balyana': 'البلينا',
  'banha': 'بنها',
  'baqliyyah': 'البقلية',
  'bardein': 'بردين',
  'bardis': 'برديس',
  'barqin': 'برقين',
  'bartas': 'برطس',
  'basandilah': 'بسنديله',
  'bashtil': 'بشتيل المحطة',
  'bashtil b': 'بشتيل البلد',
  'batanun': 'البتانون',
  'belbes': 'بلبيس',
  'belkas': 'بلقاس',
  'beni hidayr': 'بني حدير',
  'beni mazar': 'بني مزار',
  'beni salamah': 'بني سلامة',
  'beni suef': 'بني سويف',
  'berket saba': 'بركة السبع',
  'biba': 'ببا',
  'bir imarah': 'بير عمارة',
  'birijat': 'البريجات',
  'birqash': 'برقاش',
  'biyala': 'بيلا',
  'blida': 'البليدة',
  'borg el arab': 'برج العرب',
  'borg el arab airport': 'مطار برج العرب',
  'bouha': 'البوها',
  'cairo': 'القاهرة',
  'dabaa': 'الضبعة',
  'damanhour': 'دمنهور',
  'damaris': 'دماريس',
  'damietta': 'دمياط',
  'daraw': 'دراو',
  'dayr mawas': 'دير مواس',
  'dayrout': 'ديروط',
  'derwah': 'دروة',
  'desouk': 'دسوق',
  'dishna': 'دشنا',
  'ebshway': 'ابشواي',
  'edfu': 'ادفو',
  'edwah': 'العدوة',
  'el mahalla el kubra': 'المحلة الكبرى',
  'esna': 'اسنا',
  'ethaad': 'الاتحاد',
  'farshut': 'فرشوط',
  'fashn': 'الفشن',
  'fayed': 'فايد',
  'fayoum': 'الفيوم',
  'fokah': 'فوكة',
  'galaa camp': 'معسكر الجلاء',
  'galal': 'جلال',
  'gelatmah': 'الجلاتمة',
  'gezira wastanih': 'الجزيرة الوسطانية',
  'girga': 'جرجا',
  'giza': 'الجيزة',
  'hadrah': 'الحضرة',
  'hammam': 'الحمام',
  'hamoul': 'الحامول',
  'harayah raznah': 'هرية رزنة',
  'hawamdeyya': 'الحوامدية',
  'hihya': 'هيها',
  'hikal basha': 'هيكل باشا',
  'hilwasi': 'الحلواصي',
  'hilwasi b': 'الحلواصي البلد',
  'ibshan': 'ابشان',
  'inshas': 'انشاص',
  'ismailia': 'الاسماعيلية',
  'itay barud': 'ايتاي البارود',
  'jadidah': 'الجديدة',
  'jenefh': 'جنيفة',
  'kafr ammar': 'كفر عمار',
  'kafr batanun': 'كفر البتانون',
  'kafr bulin': 'كفر بولين',
  'kafr dawar': 'كفر الدوار',
  'kafr dawoud': 'كفر داود',
  'kafr el sheikh': 'كفر الشيخ',
  'kafr msalamya': 'كفر المسلمية',
  'kafr ramadah': 'كفر رمادة',
  'kafr saad': 'كفر سعد',
  'kafr sanabisah': 'كفر السنابسة',
  'kafr saqr': 'كفر صقر',
  'kafr sarawah': 'كفر صراوة',
  'kafr selim': 'كفر سليم',
  'kafr shebeen': 'كفر شبين',
  'kafr tabluha': 'كفر طبلوها',
  'kafr taha': 'كفر طحا',
  'kafr zayat': 'كفر الزيات',
  'kajuj': 'كاجوج',
  'kalabsha': 'كلابشة',
  'kamshush': 'كمشوش',
  'khatatbah': 'الخطاطبة',
  'kom abo rady': 'كوم أبو راضي',
  'kom ahmar': 'الكوم الاحمر',
  'kom halin': 'كوم حلين',
  'kom hamada': 'كوم حمادة',
  'kom ombo': 'كوم امبو',
  'kom taweel': 'الكوم الطويل',
  'luxor': 'الاقصر',
  'maghagha': 'مغاغة',
  'mahallat mousa': 'محلة موسى',
  'mahallat rouh': 'محلة روح',
  'mahallat subk': 'محلة سبك',
  'mahamid': 'المحاميد',
  'mahjar abo hammad': 'محجر ابو حماد',
  'mahsmh': 'المحسمة',
  'mallawi': 'ملوي',
  'manashi': 'المناشي',
  'manfalut': 'منفلوط',
  'manqabad': 'منقباد',
  'manshyt bakry': 'منشية البكري',
  'mansoura': 'المنصورة',
  'maragha': 'المراغة',
  'maraziq': 'المرازيق',
  'marsa matruh': 'مرسى مطروح',
  'mashtul': 'مشتول',
  'matanyah': 'المتانية',
  'matay': 'مطاي',
  'maymun': 'الميمون',
  'mazghounah': 'المزغونة',
  'meet halfa': 'ميت حلفا',
  'menyet qamh': 'منية القمح',
  'menyet sebaa': 'منية السباع',
  'minuf': 'منوف',
  'minya': 'المنيا',
  'minyat shentena ayash': 'منية شنتا عياش',
  'mit assas': 'ميت عساس',
  'mit ghamer': 'ميت غمر',
  'mit qayed': 'ميت القايد',
  'mit yazid': 'ميت يزيد',
  'modiriyat tahrir': 'مديرية التحرير',
  'mohamed baghdady': 'محمد البغدادي',
  'moharam beek': 'محرم بك',
  'monshaa': 'المنشأة',
  'monshaat abo rayyah': 'منشاة ابو رية',
  'monshaat kiram': 'منشأة الكرام',
  'murabian': 'المرابعين',
  'nafesha': 'نفيشة',
  'nagaa hammadi': 'نجع حمادي',
  'naqidi': 'النقيدي',
  'nashart': 'نشرت',
  'nasiriyah': 'الناصرية',
  'nasser': 'ناصر',
  'nawa': 'نوى',
  'nazlet khayal': 'نزلة الخيال',
  'niklah': 'نكلا',
  'ossim': 'اوسيم',
  'port said': 'بورسعيد',
  'qaha': 'قها',
  'qalyoub': 'قليوب',
  'qalyoub b': 'قليوب البلد',
  'qanatir n': 'القناطر ج',
  'qantara gharb': 'القنطرة غرب',
  'qaraqrah': 'القراقرة',
  'qassasin': 'القصاصين',
  'qata': 'القطا',
  'qata b': 'القطا البلد',
  'qena': 'قنا',
  'qift': 'قفط',
  'qilishan': 'قليشان',
  'qleen': 'قلين',
  'qleen b': 'قلين البلد',
  'qotouri': 'القطورى',
  'qotur': 'قطور',
  'quesna': 'قويسنا',
  'qus': 'قوص',
  'qusiyyah': 'القوصية',
  'radisia': 'الرديسية',
  'ragdiah': 'الرجدية',
  'ramadi': 'الرمادي',
  'ramlat injib': 'رملة الأنجب',
  'raqqah': 'الرقة',
  'ras el hekma': 'راس الحكمة',
  'ras khaleej': 'راس الخليج',
  'rawda': 'الروضة',
  'rous': 'الروس',
  'rowaysat': 'الرويسات',
  'saft hinnah': 'صفط الحنة',
  'saft inab': 'صفط العنب',
  'saft turab': 'صفط تراب',
  'sakha': 'سخا',
  'salamant': 'سلمنت',
  'samadun': 'سمادون',
  'samalut': 'سملوط',
  'samannoud': 'سمنود',
  'samla': 'سملا',
  'sandanhour': 'سندنهور',
  'sandub': 'سندوب',
  'sanhur': 'سنهور',
  'santa': 'السنطة',
  'sawah': 'الصوة',
  'segin': 'سجين',
  'senbellawein': 'السنبلاوين',
  'serapeum': 'سرابيوم',
  'shabanat': 'الشبانات',
  'shalaqan': 'شلقان',
  'shama': 'شما',
  'shanawan': 'شنوان',
  'sharawnah': 'الشراونة',
  'shatanof': 'شطانوف',
  'shawah': 'شاوة',
  'shbas': 'شباس',
  'shebeen kom n': 'شبين الكوم ج',
  'shebeen kom o': 'شبين الكوم ق',
  'shebshir hessah': 'شبشير الحصة',
  'sheikh zayed': 'الشيخ زايد',
  'shibin qanatir': 'شبين القناطر',
  'shiblanjah': 'شبلنجة',
  'shin': 'الشين',
  'shirbin': 'شربين',
  'shirshimah': 'شرشيمة',
  'shobra qubala': 'شبرا قبالة',
  'shubra el kheima': 'شبرا الخيمة',
  'sibaiyyah': 'السباعية',
  'sidfa': 'صدفا',
  'sidi abdel rahman': 'سيدي عبد الرحمن',
  'sidi gaber': 'سيدي جابر',
  'sidi ghazy': 'سيدي غازي',
  'sidi henash': 'سيدي حنيش',
  'sila': 'سيلا',
  'silwa bahari': 'سلوا',
  'sohag': 'سوهاج',
  'suds': 'سدس',
  'suez': 'السويس',
  'tafhna ashraf': 'تفهنا الاشراف',
  'taha bishah': 'طحا البيشة',
  'tahanub': 'طحانوب',
  'tahta': 'طهطا',
  'tairyyah': 'الطيرية',
  'tairyyah b': 'الطيرية البلد',
  'tal kabeer': 'التل الكبير',
  'tala': 'تلا',
  'talkha': 'طلخا',
  'tall rozan': 'تل روزن',
  'tanbadi': 'طنبدي',
  'tansa': 'طنسا',
  'tanta': 'طنطا',
  'taranis arab': 'طرانيس العرب',
  'tarranah': 'الطرانة',
  'tawfiqiah': 'التوفيقية',
  'tima': 'طما',
  'toukh': 'طوخ',
  'upper egypt': 'صعيد مصر',
  'usayrat': 'العسيرات',
  'waqid': 'واقد',
  'wasfih': 'الواصفية',
  'wasta': 'الواسطى',
  'werash': 'الورش',
  'werdan': 'وردان',
  'zagazig': 'الزقازيق',
  'zagazig university': 'جامعة الزقازيق',
  'zahawiyin': 'الزهوين',
  'zat kom': 'ذات الكوم',
  'zawya hamraa': 'الزاوية الحمراء',
  'zaytoun q': 'الزيتون ق',
  'zefta': 'زفتى',
  'zurayqi': 'الزريقي',
};

// Map from Arabic station name to English
const Map<String, String> _stationArToEn = {
  'ابا الوقف': 'Aba Wakf',
  'ابشان': 'Ibshan',
  'ابشواي': 'Ebshway',
  'ابو الخاوي': 'Abo Khawi',
  'ابو الشقوق': 'Abo Shuquq',
  'ابو تشت': 'Abo Tesht',
  'ابو تيج': 'Abo Tij',
  'ابو جريش': 'Abo Gresh',
  'ابو حماد': 'Abo Hammad',
  'ابو حمص': 'Abo Homos',
  'ابو سلطان': 'Abo Sultan',
  'ابو شوشة': 'Abo Shousha',
  'ابو صوير': 'Abo Swer',
  'ابو غالب': 'Abo Ghaleb',
  'ابو قرقاص': 'Abo Qurqas',
  'ابو كبير': 'Abo Kibir',
  'ابو مشهور': 'Abo Mashhour',
  'ابو ياسين': 'Abo Yassin',
  'ادفو': 'Edfu',
  'ارمنت': 'Armant',
  'اسنا': 'Esna',
  'اسوان': 'Aswan',
  'اسيوط': 'Assiut',
  'اشمنت': 'Ashmant',
  'اشمون': 'Ashmun',
  'اطواب': 'Atwab',
  'الاتحاد': 'Ethaad',
  'الاخماس': 'Akhmas',
  'الاسكندرية': 'Alexandria',
  'الاسماعيلية': 'Ismailia',
  'الاقصر': 'Luxor',
  'البتانون': 'Batanun',
  'البدرشين': 'Badrshein',
  'البريجات': 'Birijat',
  'البعالوة': 'Baalwh',
  'البقلية': 'Baqliyyah',
  'البليدة': 'Blida',
  'البلينا': 'Balyana',
  'البوها': 'Bouha',
  'التل الكبير': 'Tal Kabeer',
  'التوفيقية': 'Tawfiqiah',
  'الجديدة': 'Jadidah',
  'الجزيرة الوسطانية': 'Gezira Wastanih',
  'الجلاتمة': 'Gelatmah',
  'الجيزة': 'Giza',
  'الحامول': 'Hamoul',
  'الحضرة': 'Hadrah',
  'الحلواصي': 'Hilwasi',
  'الحلواصي البلد': 'Hilwasi B',
  'الحمام': 'Hammam',
  'الحوامدية': 'Hawamdeyya',
  'الخطاطبة': 'Khatatbah',
  'الرجدية': 'Ragdiah',
  'الرديسية': 'Radisia',
  'الرقة': 'Raqqah',
  'الرمادي': 'Ramadi',
  'الروس': 'Rous',
  'الروضة': 'Rawda',
  'الرويسات': 'Rowaysat',
  'الزاوية الحمراء': 'Zawya Hamraa',
  'الزريقي': 'Zurayqi',
  'الزقازيق': 'Zagazig',
  'الزنكلون': 'Az Zanklun',
  'الزهوين': 'Zahawiyin',
  'الزيتون ق': 'Zaytoun Q',
  'السباعية': 'Sibaiyyah',
  'السنبلاوين': 'Senbellawein',
  'السنطة': 'Santa',
  'السويس': 'Suez',
  'الشبانات': 'Shabanat',
  'الشراونة': 'Sharawnah',
  'الشيخ زايد': 'Sheikh Zayed',
  'الشين': 'Shin',
  'الصوة': 'Sawah',
  'الضبعة': 'Dabaa',
  'الطرانة': 'Tarranah',
  'الطيرية': 'Tairyyah',
  'الطيرية البلد': 'Tairyyah B',
  'العامرية': 'Amreyah',
  'العداوية': 'Adawyh',
  'العدوة': 'Edwah',
  'العزيزية': 'Aziziyyah',
  'العسيرات': 'Usayrat',
  'العصلوجي': 'Asluji',
  'العلمين': 'Alamein',
  'العميد': 'Ameed',
  'العياط': 'Ayat',
  'الفشن': 'Fashn',
  'الفيوم': 'Fayoum',
  'القاهرة': 'Cairo',
  'القراقرة': 'Qaraqrah',
  'القصاصين': 'Qassasin',
  'القطا': 'Qata',
  'القطا البلد': 'Qata B',
  'القطورى': 'Qotouri',
  'القناطر ج': 'Qanatir N',
  'القنطرة غرب': 'Qantara Gharb',
  'القوصية': 'Qusiyyah',
  'الكوم الاحمر': 'Kom Ahmar',
  'الكوم الطويل': 'Kom Taweel',
  'المتانية': 'Matanyah',
  'المحاميد': 'Mahamid',
  'المحسمة': 'Mahsmh',
  'المحلة الكبرى': 'El Mahalla El Kubra',
  'المرابعين': 'Murabian',
  'المرازيق': 'Maraziq',
  'المراغة': 'Maragha',
  'المزغونة': 'Mazghounah',
  'المناشي': 'Manashi',
  'المنشأة': 'Monshaa',
  'المنصورة': 'Mansoura',
  'المنيا': 'Minya',
  'الميمون': 'Maymun',
  'الناصرية': 'Nasiriyah',
  'النقيدي': 'Naqidi',
  'الواسطى': 'Wasta',
  'الواصفية': 'Wasfih',
  'الورش': 'Werash',
  'انشاص': 'Inshas',
  'اوسيم': 'Ossim',
  'اولاد سيف': 'Awlad Seif',
  'ايتاي البارود': 'Itay Barud',
  'ببا': 'Biba',
  'بدوي': 'Badawy',
  'برج العرب': 'Borg El Arab',
  'برديس': 'Bardis',
  'بردين': 'Bardein',
  'برطس': 'Bartas',
  'برقاش': 'Birqash',
  'برقين': 'Barqin',
  'بركة السبع': 'Berket Saba',
  'بسنديله': 'Basandilah',
  'بشتيل البلد': 'Bashtil B',
  'بشتيل المحطة': 'Bashtil',
  'بلانة': 'Ballana',
  'بلبيس': 'Belbes',
  'بلقاس': 'Belkas',
  'بنها': 'Banha',
  'بني حدير': 'Beni Hidayr',
  'بني سلامة': 'Beni Salamah',
  'بني سويف': 'Beni Suef',
  'بني مزار': 'Beni Mazar',
  'بورسعيد': 'Port Said',
  'بير عمارة': 'Bir Imarah',
  'بيلا': 'Biyala',
  'تفهنا الاشراف': 'Tafhna Ashraf',
  'تل روزن': 'Tall Rozan',
  'تلا': 'Tala',
  'جامع بدر': 'Badr Mosque',
  'جامعة الأزهر': 'Al-Azhar University',
  'جامعة الزقازيق': 'Zagazig University',
  'جرجا': 'Girga',
  'جلال': 'Galal',
  'جنيفة': 'Jenefh',
  'دراو': 'Daraw',
  'دروة': 'Derwah',
  'دسوق': 'Desouk',
  'دشنا': 'Dishna',
  'دماريس': 'Damaris',
  'دمنهور': 'Damanhour',
  'دمياط': 'Damietta',
  'دير مواس': 'Dayr Mawas',
  'ديروط': 'Dayrout',
  'ذات الكوم': 'Zat Kom',
  'راس الحكمة': 'Ras El Hekma',
  'راس الخليج': 'Ras Khaleej',
  'رملة الأنجب': 'Ramlat Injib',
  'زفتى': 'Zefta',
  'سجين': 'Segin',
  'سخا': 'Sakha',
  'سدس': 'Suds',
  'سرابيوم': 'Serapeum',
  'سلمنت': 'Salamant',
  'سلوا': 'Silwa Bahari',
  'سمادون': 'Samadun',
  'سملا': 'Samla',
  'سملوط': 'Samalut',
  'سمنود': 'Samannoud',
  'سندنهور': 'Sandanhour',
  'سندوب': 'Sandub',
  'سنهور': 'Sanhur',
  'سوهاج': 'Sohag',
  'سيدي جابر': 'Sidi Gaber',
  'سيدي حنيش': 'Sidi Henash',
  'سيدي عبد الرحمن': 'Sidi Abdel Rahman',
  'سيدي غازي': 'Sidi Ghazy',
  'سيلا': 'Sila',
  'شاوة': 'Shawah',
  'شباس': 'Shbas',
  'شبرا الخيمة': 'Shubra El Kheima',
  'شبرا قبالة': 'Shobra Qubala',
  'شبشير الحصة': 'Shebshir Hessah',
  'شبلنجة': 'Shiblanjah',
  'شبين القناطر': 'Shibin Qanatir',
  'شبين الكوم ج': 'Shebeen Kom N',
  'شبين الكوم ق': 'Shebeen Kom O',
  'شربين': 'Shirbin',
  'شرشيمة': 'Shirshimah',
  'شطانوف': 'Shatanof',
  'شلقان': 'Shalaqan',
  'شما': 'Shama',
  'شنوان': 'Shanawan',
  'صدفا': 'Sidfa',
  'صعيد مصر': 'Upper Egypt',
  'صفط الحنة': 'Saft Hinnah',
  'صفط العنب': 'Saft Inab',
  'صفط تراب': 'Saft Turab',
  'طحا البيشة': 'Taha Bishah',
  'طحانوب': 'Tahanub',
  'طرانيس العرب': 'Taranis Arab',
  'طلخا': 'Talkha',
  'طما': 'Tima',
  'طنبدي': 'Tanbadi',
  'طنسا': 'Tansa',
  'طنطا': 'Tanta',
  'طهطا': 'Tahta',
  'طوخ': 'Toukh',
  'عامرية الفيوم': 'Amereyat El Fayoum',
  'عرب الرمل': 'Arab Raml',
  'فايد': 'Fayed',
  'فرشوط': 'Farshut',
  'فوكة': 'Fokah',
  'قطور': 'Qotur',
  'قفط': 'Qift',
  'قليشان': 'Qilishan',
  'قلين': 'Qleen',
  'قلين البلد': 'Qleen B',
  'قليوب': 'Qalyoub',
  'قليوب البلد': 'Qalyoub B',
  'قنا': 'Qena',
  'قها': 'Qaha',
  'قوص': 'Qus',
  'قويسنا': 'Quesna',
  'كاجوج': 'Kajuj',
  'كفر البتانون': 'Kafr Batanun',
  'كفر الدوار': 'Kafr Dawar',
  'كفر الزيات': 'Kafr Zayat',
  'كفر السنابسة': 'Kafr Sanabisah',
  'كفر الشيخ': 'Kafr El Sheikh',
  'كفر المسلمية': 'Kafr Msalamya',
  'كفر بولين': 'Kafr Bulin',
  'كفر داود': 'Kafr Dawoud',
  'كفر رمادة': 'Kafr Ramadah',
  'كفر سعد': 'Kafr Saad',
  'كفر سليم': 'Kafr Selim',
  'كفر شبين': 'Kafr Shebeen',
  'كفر صراوة': 'Kafr Sarawah',
  'كفر صقر': 'Kafr Saqr',
  'كفر طبلوها': 'Kafr Tabluha',
  'كفر طحا': 'Kafr Taha',
  'كفر عمار': 'Kafr Ammar',
  'كلابشة': 'Kalabsha',
  'كمشوش': 'Kamshush',
  'كوم أبو راضي': 'Kom Abo Rady',
  'كوم امبو': 'Kom Ombo',
  'كوم حلين': 'Kom Halin',
  'كوم حمادة': 'Kom Hamada',
  'محجر ابو حماد': 'Mahjar Abo Hammad',
  'محرم بك': 'Moharam Beek',
  'محلة روح': 'Mahallat Rouh',
  'محلة سبك': 'Mahallat Subk',
  'محلة موسى': 'Mahallat Mousa',
  'محمد البغدادي': 'Mohamed Baghdady',
  'مديرية التحرير': 'Modiriyat Tahrir',
  'مرسى مطروح': 'Marsa Matruh',
  'مشتول': 'Mashtul',
  'مطار برج العرب': 'Borg El Arab Airport',
  'مطاي': 'Matay',
  'معسكر الجلاء': 'Galaa Camp',
  'مغاغة': 'Maghagha',
  'ملوي': 'Mallawi',
  'منشأة الكرام': 'Monshaat Kiram',
  'منشاة ابو رية': 'Monshaat Abo Rayyah',
  'منشية البكري': 'Manshyt Bakry',
  'منفلوط': 'Manfalut',
  'منقباد': 'Manqabad',
  'منوف': 'Minuf',
  'منية السباع': 'Menyet Sebaa',
  'منية القمح': 'Menyet Qamh',
  'منية شنتا عياش': 'Minyat Shentena Ayash',
  'ميت القايد': 'Mit Qayed',
  'ميت حلفا': 'Meet Halfa',
  'ميت عساس': 'Mit Assas',
  'ميت غمر': 'Mit Ghamer',
  'ميت يزيد': 'Mit Yazid',
  'ناصر': 'Nasser',
  'نجع حمادي': 'Nagaa Hammadi',
  'نزلة الخيال': 'Nazlet Khayal',
  'نشرت': 'Nashart',
  'نفيشة': 'Nafesha',
  'نكلا': 'Niklah',
  'نوى': 'Nawa',
  'هرية رزنة': 'Harayah Raznah',
  'هيكل باشا': 'Hikal Basha',
  'هيها': 'Hihya',
  'واقد': 'Waqid',
  'وردان': 'Werdan',
  'أبو تيج': 'Abu Tig',
  'شطورة': 'Shatourah',
  'بلصفورة': 'Balasfurah',
  'نادي السكة': 'Nadi El Seka',
  'عبد القادر': 'Abd El Qader',
  'سماد أبو قير': 'Abo Qir Fertilizer',
  'بهيج': 'Baheeg',
};

extension StationHelper on String {
  String toLocalizedStation(BuildContext context) {
    if (context.isArabic) {
      return _stationEnToAr[toLowerCase()] ?? this;
    } else {
      return _stationArToEn[this] ?? this;
    }
  }
}
