import 'dart:typed_data';
import 'dart:ui' as ui;

import 'package:flutter/material.dart';
import 'package:intl/intl.dart';
import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;
import 'package:printing/printing.dart';
import 'package:qr_flutter/qr_flutter.dart';
import 'package:transportation_app/features/my_tickets/presentation/views/widgets/boarding_pass_helpers.dart';
import 'package:transportation_app/features/my_tickets/domain/entities/ticket_entity.dart';

class BoardingPassPdfService {
  final TicketEntity ticket;
  final TicketPassengerEntity passenger;

  const BoardingPassPdfService({
    required this.ticket,
    required this.passenger,
  });

  Future<void> printPdf(String qrPayload) async {
    final pdf = await _buildPdf(qrPayload);

    await Printing.layoutPdf(
      onLayout: (_) async => pdf.save(),
      name: _fileName,
    );
  }

  Future<void> sharePdf(String qrPayload) async {
    final pdf = await _buildPdf(qrPayload);
    final bytes = await pdf.save();

    await Printing.sharePdf(bytes: bytes, filename: _fileName);
  }

  Future<pw.Document> _buildPdf(String qrPayload) async {
    final pdf = pw.Document();
    final qrImage = await _generateQrImage(qrPayload);

    pdf.addPage(
      pw.Page(
        pageFormat: PdfPageFormat.a4,
        margin: const pw.EdgeInsets.all(32),
        build: (_) => pw.Column(
          crossAxisAlignment: pw.CrossAxisAlignment.start,
          children: [
            _buildHeader(),
            pw.SizedBox(height: 24),
            pw.Divider(),
            pw.SizedBox(height: 16),
            _buildRoute(),
            pw.SizedBox(height: 24),
            pw.Divider(),
            pw.SizedBox(height: 16),
            _buildPassenger(qrImage),
            pw.SizedBox(height: 24),
            pw.Divider(),
            pw.SizedBox(height: 8),
            pw.Text(
              'Generated by TransportApp - ${_formatPdfDateTime(DateTime.now())}',
              style: const pw.TextStyle(fontSize: 9, color: PdfColors.grey400),
            ),
          ],
        ),
      ),
    );

    return pdf;
  }

  pw.Widget _buildHeader() {
    return pw.Row(
      mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
      children: [
        pw.Column(
          crossAxisAlignment: pw.CrossAxisAlignment.start,
          children: [
            pw.Text(
              'BOARDING PASS',
              style: pw.TextStyle(fontSize: 22, fontWeight: pw.FontWeight.bold),
            ),
            pw.Text(
              _agencyName,
              style: const pw.TextStyle(fontSize: 14, color: PdfColors.grey600),
            ),
          ],
        ),
        pw.Text(
          'REF-${ticket.bookingId}',
          style: const pw.TextStyle(fontSize: 12, color: PdfColors.grey600),
        ),
      ],
    );
  }

  pw.Widget _buildRoute() {
    return pw.Row(
      mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
      children: [
        _buildPdfStop(
          code: boardingPassLocationCode(_originGovernorate),
          governorate: _originGovernorate,
          station: _originStation,
          time: _formatPdfTime(ticket.boardingTime),
        ),
        pw.Text(
          '->',
          style: const pw.TextStyle(fontSize: 28, color: PdfColors.grey),
        ),
        _buildPdfStop(
          code: boardingPassLocationCode(_destinationGovernorate),
          governorate: _destinationGovernorate,
          station: _destinationStation,
          time: _formatPdfTime(ticket.dropoffTime),
          alignEnd: true,
        ),
      ],
    );
  }

  pw.Widget _buildPdfStop({
    required String code,
    required String governorate,
    required String station,
    required String time,
    bool alignEnd = false,
  }) {
    return pw.Column(
      crossAxisAlignment: alignEnd
          ? pw.CrossAxisAlignment.end
          : pw.CrossAxisAlignment.start,
      children: [
        pw.Text(
          code,
          style: pw.TextStyle(fontSize: 36, fontWeight: pw.FontWeight.bold),
        ),
        pw.Text(governorate),
        if (station.isNotEmpty)
          pw.Text(
            station,
            style: const pw.TextStyle(fontSize: 10, color: PdfColors.grey600),
          ),
        pw.Text(
          time,
          style: pw.TextStyle(fontSize: 16, fontWeight: pw.FontWeight.bold),
        ),
      ],
    );
  }

  pw.Widget _buildPassenger(Uint8List? qrImage) {
    return pw.Row(
      crossAxisAlignment: pw.CrossAxisAlignment.start,
      children: [
        pw.Expanded(
          child: pw.Column(
            crossAxisAlignment: pw.CrossAxisAlignment.start,
            children: [
              pw.Text(
                'PASSENGER',
                style: const pw.TextStyle(fontSize: 10, color: PdfColors.grey),
              ),
              pw.SizedBox(height: 4),
              pw.Text(
                _passengerName,
                style: pw.TextStyle(
                  fontSize: 20,
                  fontWeight: pw.FontWeight.bold,
                ),
              ),
              if (_passengerIdNumber != '-') ...[
                pw.SizedBox(height: 4),
                pw.Text(
                  'ID: $_passengerIdNumber',
                  style: const pw.TextStyle(
                    fontSize: 12,
                    color: PdfColors.grey600,
                  ),
                ),
              ],
              pw.SizedBox(height: 16),
              pw.Row(
                children: [
                  _pdfChip(
                    'SEAT',
                    _englishPdfText(passenger.seatNumber),
                  ),
                  pw.SizedBox(width: 16),
                  _pdfChip('CLASS', _englishPdfText(ticket.className)),
                  pw.SizedBox(width: 16),
                  _pdfChip('DATE', _formatPdfDate(ticket.boardingTime)),
                ],
              ),
            ],
          ),
        ),
        if (qrImage != null)
          pw.Image(pw.MemoryImage(qrImage), width: 120, height: 120),
      ],
    );
  }

  Future<Uint8List?> _generateQrImage(String data) async {
    try {
      final qrPainter = QrPainter(
        data: data,
        version: QrVersions.auto,
        gapless: true,
        eyeStyle: const QrEyeStyle(
          eyeShape: QrEyeShape.square,
          color: Color(0xFF000000),
        ),
        dataModuleStyle: const QrDataModuleStyle(
          dataModuleShape: QrDataModuleShape.square,
          color: Color(0xFF000000),
        ),
      );
      final recorder = ui.PictureRecorder();
      final canvas = ui.Canvas(
        recorder,
        const ui.Rect.fromLTWH(0, 0, 300, 300),
      );
      qrPainter.paint(canvas, const ui.Size(300, 300));
      final picture = recorder.endRecording();
      final image = await picture.toImage(300, 300);
      final byteData = await image.toByteData(format: ui.ImageByteFormat.png);
      return byteData?.buffer.asUint8List();
    } catch (_) {
      return null;
    }
  }

  pw.Widget _pdfChip(String label, String value) {
    return pw.Column(
      crossAxisAlignment: pw.CrossAxisAlignment.start,
      children: [
        pw.Text(
          label,
          style: const pw.TextStyle(fontSize: 9, color: PdfColors.grey),
        ),
        pw.Text(
          value,
          style: pw.TextStyle(fontSize: 13, fontWeight: pw.FontWeight.bold),
        ),
      ],
    );
  }

  String get _fileName => 'boarding-pass-$_fileSafePassengerName.pdf';

  String get _fileSafePassengerName {
    final safeName = _passengerName
        .replaceAll(RegExp(r'[^A-Za-z0-9_-]+'), '_')
        .replaceAll(RegExp(r'_+'), '_')
        .replaceAll(RegExp(r'^_|_$'), '');
    return safeName.isNotEmpty && safeName != '-' ? safeName : 'passenger';
  }

  String get _passengerName => _englishPdfText(passenger.name);

  String get _passengerIdNumber => _englishPdfText(passenger.idNumber);

  String get _agencyName => _englishPdfText(ticket.agencyName);

  String get _originGovernorate => _englishPdfText(ticket.originGovernorate);

  String get _originStation => _englishPdfText(ticket.originStation);

  String get _destinationGovernorate =>
      _englishPdfText(ticket.destinationGovernorate);

  String get _destinationStation => _englishPdfText(ticket.destinationStation);

  String _formatPdfTime(DateTime dateTime) =>
      DateFormat('hh:mm a', 'en_US').format(dateTime);

  String _formatPdfDate(DateTime dateTime) =>
      DateFormat('dd MMM yyyy', 'en_US').format(dateTime);

  String _formatPdfDateTime(DateTime dateTime) =>
      DateFormat('dd MMM yyyy, hh:mm a', 'en_US').format(dateTime);

  String _englishPdfText(String value) {
    final trimmed = value.trim();
    if (trimmed.isEmpty || RegExp(r'[\u0600-\u06FF]').hasMatch(trimmed)) {
      return '-';
    }
    final asciiOnly = trimmed
        .replaceAll(RegExp(r'[^\x20-\x7E]'), '')
        .replaceAll(RegExp(r'\s+'), ' ')
        .trim();
    return asciiOnly.isEmpty ? '-' : asciiOnly;
  }
}
