import 'dart:typed_data';
import 'dart:ui' as ui;

import 'package:flutter/material.dart';
import 'package:intl/intl.dart';
import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;
import 'package:printing/printing.dart';
import 'package:qr_flutter/qr_flutter.dart';
import 'package:transportation_app/features/my_tickets/presentation/views/widgets/boarding_pass_helpers.dart';
import 'package:transportation_app/features/my_tickets/domain/entities/ticket_entity.dart';

class BoardingPassPdfService {
  final TicketEntity ticket;
  final TicketPassengerEntity passenger;
  final bool isArabic;

  const BoardingPassPdfService({
    required this.ticket,
    required this.passenger,
    required this.isArabic,
  });

  Future<void> printPdf(String qrPayload) async {
    final pdf = await _buildPdf(qrPayload);

    await Printing.layoutPdf(
      onLayout: (_) async => pdf.save(),
      name: _fileName,
    );
  }

  Future<void> sharePdf(String qrPayload) async {
    final pdf = await _buildPdf(qrPayload);
    final bytes = await pdf.save();

    await Printing.sharePdf(bytes: bytes, filename: _fileName);
  }

  Future<pw.Document> _buildPdf(String qrPayload) async {
    final pdf = pw.Document();
    final qrImage = await _generateQrImage(qrPayload);

    pdf.addPage(
      pw.Page(
        pageFormat: PdfPageFormat.a4,
        margin: const pw.EdgeInsets.all(32),
        build: (_) => pw.Column(
          crossAxisAlignment: pw.CrossAxisAlignment.start,
          children: [
            _buildHeader(),
            pw.SizedBox(height: 24),
            pw.Divider(),
            pw.SizedBox(height: 16),
            _buildRoute(),
            pw.SizedBox(height: 24),
            pw.Divider(),
            pw.SizedBox(height: 16),
            _buildPassenger(qrImage),
            pw.SizedBox(height: 24),
            pw.Divider(),
            pw.SizedBox(height: 8),
            pw.Text(
              'Generated by TransportApp - ${DateFormat('dd MMM yyyy, hh:mm a').format(DateTime.now())}',
              style: const pw.TextStyle(fontSize: 9, color: PdfColors.grey400),
            ),
          ],
        ),
      ),
    );

    return pdf;
  }

  pw.Widget _buildHeader() {
    return pw.Row(
      mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
      children: [
        pw.Column(
          crossAxisAlignment: pw.CrossAxisAlignment.start,
          children: [
            pw.Text(
              'BOARDING PASS',
              style: pw.TextStyle(fontSize: 22, fontWeight: pw.FontWeight.bold),
            ),
            pw.Text(
              _agencyName,
              style: const pw.TextStyle(fontSize: 14, color: PdfColors.grey600),
            ),
          ],
        ),
        pw.Text(
          'REF-${ticket.bookingId}',
          style: const pw.TextStyle(fontSize: 12, color: PdfColors.grey600),
        ),
      ],
    );
  }

  pw.Widget _buildRoute() {
    return pw.Row(
      mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
      children: [
        _buildPdfStop(
          code: boardingPassLocationCode(_originGovernorate),
          governorate: _originGovernorate,
          station: _originStation,
          time: formatBoardingPassTime(ticket.boardingTime),
        ),
        pw.Text(
          '->',
          style: const pw.TextStyle(fontSize: 28, color: PdfColors.grey),
        ),
        _buildPdfStop(
          code: boardingPassLocationCode(_destinationGovernorate),
          governorate: _destinationGovernorate,
          station: _destinationStation,
          time: formatBoardingPassTime(ticket.dropoffTime),
          alignEnd: true,
        ),
      ],
    );
  }

  pw.Widget _buildPdfStop({
    required String code,
    required String governorate,
    required String station,
    required String time,
    bool alignEnd = false,
  }) {
    return pw.Column(
      crossAxisAlignment: alignEnd
          ? pw.CrossAxisAlignment.end
          : pw.CrossAxisAlignment.start,
      children: [
        pw.Text(
          code,
          style: pw.TextStyle(fontSize: 36, fontWeight: pw.FontWeight.bold),
        ),
        pw.Text(governorate),
        if (station.isNotEmpty)
          pw.Text(
            station,
            style: const pw.TextStyle(fontSize: 10, color: PdfColors.grey600),
          ),
        pw.Text(
          time,
          style: pw.TextStyle(fontSize: 16, fontWeight: pw.FontWeight.bold),
        ),
      ],
    );
  }

  pw.Widget _buildPassenger(Uint8List? qrImage) {
    return pw.Row(
      crossAxisAlignment: pw.CrossAxisAlignment.start,
      children: [
        pw.Expanded(
          child: pw.Column(
            crossAxisAlignment: pw.CrossAxisAlignment.start,
            children: [
              pw.Text(
                'PASSENGER',
                style: const pw.TextStyle(fontSize: 10, color: PdfColors.grey),
              ),
              pw.SizedBox(height: 4),
              pw.Text(
                passenger.name.isNotEmpty ? passenger.name : '-',
                style: pw.TextStyle(
                  fontSize: 20,
                  fontWeight: pw.FontWeight.bold,
                ),
              ),
              if (passenger.idNumber.isNotEmpty) ...[
                pw.SizedBox(height: 4),
                pw.Text(
                  'ID: ${passenger.idNumber}',
                  style: const pw.TextStyle(
                    fontSize: 12,
                    color: PdfColors.grey600,
                  ),
                ),
              ],
              pw.SizedBox(height: 16),
              pw.Row(
                children: [
                  _pdfChip(
                    'SEAT',
                    passenger.seatNumber.isNotEmpty
                        ? passenger.seatNumber
                        : '-',
                  ),
                  pw.SizedBox(width: 16),
                  _pdfChip(
                    'CLASS',
                    ticket.className.isNotEmpty ? ticket.className : '-',
                  ),
                  pw.SizedBox(width: 16),
                  _pdfChip('DATE', formatBoardingPassDate(ticket.boardingTime)),
                ],
              ),
            ],
          ),
        ),
        if (qrImage != null)
          pw.Image(pw.MemoryImage(qrImage), width: 120, height: 120),
      ],
    );
  }

  Future<Uint8List?> _generateQrImage(String data) async {
    try {
      final qrPainter = QrPainter(
        data: data,
        version: QrVersions.auto,
        gapless: true,
        eyeStyle: const QrEyeStyle(
          eyeShape: QrEyeShape.square,
          color: Color(0xFF000000),
        ),
        dataModuleStyle: const QrDataModuleStyle(
          dataModuleShape: QrDataModuleShape.square,
          color: Color(0xFF000000),
        ),
      );
      final recorder = ui.PictureRecorder();
      final canvas = ui.Canvas(
        recorder,
        const ui.Rect.fromLTWH(0, 0, 300, 300),
      );
      qrPainter.paint(canvas, const ui.Size(300, 300));
      final picture = recorder.endRecording();
      final image = await picture.toImage(300, 300);
      final byteData = await image.toByteData(format: ui.ImageByteFormat.png);
      return byteData?.buffer.asUint8List();
    } catch (_) {
      return null;
    }
  }

  pw.Widget _pdfChip(String label, String value) {
    return pw.Column(
      crossAxisAlignment: pw.CrossAxisAlignment.start,
      children: [
        pw.Text(
          label,
          style: const pw.TextStyle(fontSize: 9, color: PdfColors.grey),
        ),
        pw.Text(
          value,
          style: pw.TextStyle(fontSize: 13, fontWeight: pw.FontWeight.bold),
        ),
      ],
    );
  }

  String get _fileName =>
      'boarding-pass-${passenger.name.replaceAll(' ', '_')}.pdf';

  String get _agencyName =>
      isArabic ? (ticket.agencyNameAr ?? ticket.agencyName) : ticket.agencyName;

  String get _originGovernorate => isArabic
      ? (ticket.originGovernorateAr ?? ticket.originGovernorate)
      : ticket.originGovernorate;

  String get _originStation => isArabic
      ? (ticket.originStationNameAr ?? ticket.originStation)
      : ticket.originStation;

  String get _destinationGovernorate => isArabic
      ? (ticket.destinationGovernorateAr ?? ticket.destinationGovernorate)
      : ticket.destinationGovernorate;

  String get _destinationStation => isArabic
      ? (ticket.destinationStationNameAr ?? ticket.destinationStation)
      : ticket.destinationStation;
}
